Item dispenser fixes #10 and #11
LlewVallis/OpenMissileWars pull request #13
Opened 2020-11-17 17:16 UTC by Simetraa

2020-11-18 10:50 UTC, LlewVallis requested changes
Few issues here:

1. It's possible to have arrow stacks greater than three in size. This looks like it'll truncate stacks down unduly.
2. This doesn't look like it'll send a message to the player if they miss out on arrows due to having too many. Also I believe the display name for an arrow stack is "Arrow" (the message should say "Arrows") so that would cause issues even if there were arrow messages.

2020-11-18 10:50 UTC, LlewVallis commented on plugin/src/main/java/org/astropeci/omw/item/PeriodicItemDispenser.java
> +            } else if(item.getType() == Material.ARROW) {
```suggestion
            } else if (item.getType() == Material.ARROW) {
```
Slight formatting typo, see the main comment for other issues.

2020-11-18 11:57 UTC, Simetraa commented
> This doesn't look like it'll send a message to the player if they miss out on arrows due to having too many. Also I believe the display name for an arrow stack is "Arrow" (the message should say "Arrows") so that would cause issues even if there were arrow messages.

Should it send the same message (" already obtained!") if topping up arrows? I checked on CK and it does not send any message.

2020-11-19 02:17 UTC, LlewVallis commented
> > This doesn't look like it'll send a message to the player if they miss out on arrows due to having too many. Also I believe the display name for an arrow stack is "Arrow" (the message should say "Arrows") so that would cause issues even if there were arrow messages.
> 
> Should it send the same message (" already obtained!") if topping up arrows? I checked on CK and it does not send any message.

Yes and no, it should only send the "already obtained" message for arrows if the player already has three or more in their inventory (and hence doesn't receive any extras).

2020-11-19 02:22 UTC, LlewVallis reviewed
Looks good at this point! Thanks :) I'll fully test and merge the changes when I have a chance.

2020-11-23 14:57 UTC, merged

2020-11-23 14:58 UTC, LlewVallis commented
I've validated that everything is correct and working, and hence have merged it into master. Thanks for the contribution!